### ISSUE TITLE
ValidationError: Additional properties are not allowed (e.g. 'age')

### ISSUE THREAD

**Issue by kilpert** [KohlbacherLab/dnpm-dip-api-gateway#4]
The provided patient record examples (https://dnpm.bwhealthcloud.de/api/rd/fake/data/patient-record) do validate with the provided json schema (https://dnpm.bwhealthcloud.de/api/rd/etl/patient-record/schema). I tested some online validators and in python. Some validation errors show up, e.g. here using python:

```
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('age', 'vitalStatus' were unexpected)

Failed validating 'additionalProperties' in schema['properties']['patient']:
    {'$anchor': 'Patient',
     'properties': {'dateOfDeath': {'type': 'string', 'format': 'date'},
                    'healthInsurance': {'$ref': '#Reference'},
                    'address': {'type': 'object',
                                'additionalProperties': False,
                                'properties': {'municipalityCode': {'type': 'string'}},
                                'required': ['municipalityCode']},
                    'birthDate': {'type': 'string', 'format': 'date'},
                    'id': {'$ref': '#Id'},
                    'gender': {'$ref': '#Coding_Gender'},
                    'managingSite': {'$ref': '#Coding'}},
     'additionalProperties': False,
     'type': 'object',
     'required': ['id', 'gender', 'birthDate']}

On instance['patient']:
    {'id': 'a1194acd-7586-4e47-b5b2-b29ed792586e',
     'gender': {'code': 'female',
                'display': 'Weiblich',
                'system': 'Gender'},
     'birthDate': '1997-02-07',
     'age': {'value': 27, 'unit': 'Years'},
     'vitalStatus': {'code': 'alive',
                     'display': 'Lebend',
                     'system': 'dnpm-dip/patient/vital-status'}}
```

Here, an online validator (https://www.jsonschemavalidator.net/s/G5btPpyl) found 5 errors:

```
Found 5 error(s)

Message:
    Property 'age' has not been defined and the schema does not allow additional properties.
Schema path:
    RD-Patient-Record#Patient/additionalProperties

Message:
    Property 'vitalStatus' has not been defined and the schema does not allow additional properties.
Schema path:
    RD-Patient-Record#Patient/additionalProperties

Message:
    String '2024-04' does not validate against format 'date'.
Schema path:
    RD-Patient-Record#YearMonth/format

Message:
    String '2024-04' does not validate against format 'date'.
Schema path:
    RD-Patient-Record#YearMonth/format

Message:
    String '2024-04' does not validate against format 'date'.
Schema path:
    RD-Patient-Record#YearMonth/format
```

When I manually remove these from the patient record json, it validates fine.

**Comment by lucienclin** [comment]
Thank you for the issue report.

1) The problem with the "additional properties" is the following: The generation of these JSON schemas is based on the library [scala-jsonschema](https://github.com/andyglow/scala-jsonschema). By default, this sets "additionalProperties" to `false` on each (sub-)object's schema.
However, the _dynamic_ properties Patient.age and Patient.vitalStatus (respectively derived from birthdate and dateOfDeath) are useful for display of a Patient, and are thus added [automatically upon JSON serialization of a PatientRecord](https://github.com/KohlbacherLab/dnpm-dip-core/blob/main/src/main/scala/de/dnpm/dip/model/Patient.scala#L67) object.
This leads to this inconsistency between the available JSON schema and random generated PatientRecord JSON examples.

2) Concerning the data format error: Some date properties in the domain model are only defined to a granularity of YYYY-MM (using [Java YearMonth](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/time/YearMonth.html) in the DTO implementation). However, since JSON/ JSON Schema lacks a type for this, type `date` is used (somewhat inconsistently) in the schema generation.

I don't have any proper solution to these points a.t.m and would thus ask you to accept theses inconsistency for now.
