### ISSUE TITLE
Validation Error: using API endpoint patient-record:validate

### ISSUE THREAD

**Issue by kilpert** [KohlbacherLab/dnpm-dip-api-gateway#8]
I tried to validate a just downloaded patient-record against the API endpoint. But the response makes no sense, which makes me believe that the download schema is not correct.

Here is what I do (with python script). These are the main steps:

  1. Download the schema
  `GET https://dnpm.bwhealthcloud.de/api/rd/etl/patient-record/schema` 
  => 200 OK
  2. Download the patient-record
  `GET https://dnpm.bwhealthcloud.de/api/rd/fake/data/patient-record?format=application/json%2Bv2`
  => 200 OK
  3. But when I try to validate the just downloaded parient-record (`headers={"Accept": "*/*", "Content-type": "application/json+v2"}`; the json payload is the patient-record from 2.).
  `POST https://dnpm.bwhealthcloud.de/api/rd/etl/patient-record:validate`
  => 200 OK

  ... the response is weird:

### Problem A:

From 3., I also get this response json:

```
{
    "patient": "64abb4fd-1de4-4167-a762-d339b30b8631",
    "issues": [
        {
            "severity": "warning",
            "message": "Fehlende Angabe 'Krankenkasse'",
            "path": "/Patient[64abb4fd-1de4-4167-a762-d339b30b8631]/Krankenkasse"
        },
        {
            "severity": "info",
            "message": "Fehlende optionale Angabe 'Todesdatum', ggf. nachpr\u00fcfen, ob nachzureichen",
            "path": "/Patient[64abb4fd-1de4-4167-a762-d339b30b8631]/Todesdatum"
        }
    ],
    "createdAt": "2024-10-17T12:58:57.532494Z"
}
```
This does make no sense, because "Krankenkasse" is not defined in the schema! At least not in the schema that one can download in 1.

**Is the downloadable schema the same that is used for validation??? If not, how can we download the correct schema that was actually used?**

### Problem B:

The API endpoint in 3. does not validate properly; there are no reported errors. If validating locally in python using `jsonschema.validate(patient_record, schema)`, there are 2 issues on **age** and **vitalStatus**:

```
Traceback (most recent call last):
  File "/vol/huge/Modellvorhaben/dnpm_dip_se/dnpm_dip_seq_api.py", line 206, in <module>
    print(jsonschema.validate(d_patient_record, d_schema))
  File "/home/kilpert/miniforge3/lib/python3.10/site-packages/jsonschema/validators.py", line 1332, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('age', 'vitalStatus' were unexpected)

Failed validating 'additionalProperties' in schema['properties']['patient']:
    {'$anchor': 'Patient',
     'additionalProperties': False,
     'properties': {'address': {'additionalProperties': False,
                                'properties': {'municipalityCode': {'type': 'string'}},
                                'required': ['municipalityCode'],
                                'type': 'object'},
                    'birthDate': {'format': 'date', 'type': 'string'},
                    'dateOfDeath': {'format': 'date', 'type': 'string'},
                    'gender': {'$ref': '#Coding_Gender'},
                    'healthInsurance': {'$ref': '#Reference'},
                    'id': {'$ref': '#Id'},
                    'managingSite': {'$ref': '#Coding'}},
     'required': ['id', 'gender', 'birthDate'],
     'type': 'object'}

On instance['patient']:
    {'age': {'unit': 'Years', 'value': 37},
     'birthDate': '1987-03-30',
     'gender': {'code': 'female',
                'display': 'Weiblich',
                'system': 'Gender'},
     'id': '8fb09ba6-dc92-4905-80c5-81b5aef98e0a',
     'vitalStatus': {'code': 'alive',
                     'display': 'Lebend',
                     'system': 'dnpm-dip/patient/vital-status'}}

```

**However, none of these issues are raised by the validate API endpoint! Again, this is an indication that a wrong schema was used for validation.**

**Comment by lucienclin** [comment]
Again, thanks for checking this so thoroughly.

This requires a longer explanation, though:

The "validation" logic exposed by this validation endpoint is two-fold: After _syntactic_ validation (i.e. if the payload can be properly deserialized as a PatientRecord upload) there is a _semantic_ validation step.

This is required for various reasons:

Many of the attributes are made _optional_ on the syntactic level, even though they are _semantically_ required in order for a data set to be meaningful. The reason this was made so, is to separate concerns: Say you are an ETL developer in charge of extracting the data from respective primary systems and send them to the node backend. If this upload were to fail because _semantically_ required attributes are missing due to _incomplete documentation_ in the patient record, you'd be receiving upload errors for which you can't really do anything.
Instead, such errors pertaining to the content of a patient record are raised in the "data quality issue report" created in the semantic validation step and (aside from being returned in the upload response) are stored in the validation module of the DNPM node. The idea is that these data quality issue reports be made available to _documentarists_ in charge of completing/correcting the patient records accordingly.
In contrast to syntactic validation errors, which would ultimately be dependent on the validation/deserialization library used, and whose content is developer- but not documentarist-friendly, these issue reports are specifically created with German error messages in order to be understandable by such documentarists.
This is why in your above example, the error says "Fehlende Angabe 'Krankenkasse'" or "...Todesdatum", corresponding to missing attributes `Patient.healthInsurance` and `Patient.dateOfDeath`, which _are_ defined in the schema.

Even though it's not incorporated yet, the portal will contain sub-portals for the respeective validation module, so that documentarists can log in and see which patient record have data quality issues to be fixed.

Does this answer your question?

**Comment by lucienclin** [comment]
P.S. Concerning Problem B:

I already explained the reason for this "inconsistency" with PAtient.age and Patient.vitalStatus in another comment: https://github.com/KohlbacherLab/dnpm-dip-api-gateway/issues/4#issuecomment-2378930499

**Comment by lucienclin** [comment]
Yes, the first step upon reception of an upload request is to perform syntactic validation.
However, strictly speaking in technical terms, this doesn't use the JSON schema _per se_: The application tries to deserialize the payload as a PatientRecord data transfer object (DTO).
If this succeeds, this implies that the JSON is syntactically correct and the DTO is handed over to the semantic validation module; if it fails, the errors are returned in the HTTP response, e.g.:
```json
{
    "issues": [
        {
            "details": "/patient/gender: error.path.missing",
            "severity": "error"
        },
        {
            "details": "/diagnoses(0)/code: error.path.missing",
            "severity": "error"
        }
    ]
}
```
Accordingly, as said, this doesn't use the JSON schema itself -- but given that the JSON schema is _derived_ from the DTO and thus directly reflects the structure of expected payloads, the deserialization check is equivalent to "schema validation". Also, in your local development process, conformance with the schema (which you can check locally with the tool of your choice) also ensures that the payload will be syntactically correct for API upload.                                           

Thus, to address your points:

Re "line numbers" in the errors: Aside from the fact that I strongly assume most HTTP tools might strip line breaks or other formatting when parsing JSON input to write to a HTTP request anyway, line breaks or other formatting is certainly disregarded by the parser of the used JSON library. This is why errors are given in _JSON path_ syntax, indicating the position in the JSON tree using the name of variables according to the JSON structure/schema. This is not dependent on particular formatting of the input and thus much more meaningful i.m.h.o

Re "user perspective": These errors _are_ the "original error messages" of the syntactic validation step, i.e. the errors raised by the JSON deserializer. If the JSON payload is syntactically incorrect (cannot be parsed as DTO) it never reaches the semantic validation module. Also, the errors returned there are not just translations of the syntactic errors, but point out content-related errors, and as said, they are meant for a different class of users.
Aside from the different language, this difference of "error addressee" is also reflected by the different HTTP status codes, to allow corresponding handling in the local process:
- `400 Bad Request` indicates errors concerning the ETL developer (syntactical incorrectness or e.g. breaks of referential integrity)
- `201` or `422` indicate more or less severe _semantic_ issues, and thus concern documentarists. At this point, the handling process is in principle up to each site: Some kind of data quality improvement loop must be established. Whether this consists in having documentarists in charge to regularly check the data quality issue reports in the node's (upcoming) validation portal and proceed from there to correct the data in primary systems, or that the ETL setup be adapted to forward the data quality issue report returned in the error response into a corresponding local "workflow", is up to each site.

I agree that the API documentation on this has to be elaborated in order to make this clearer, and will do so starting next week.

About your request that the JSON schema should "at least [...] in determining whether the dataset is complete", I must point out that the schemas, i.e. the overall structure but especially also cardinalities of elements are _provisional_ (see the (NOTE here)[https://github.com/KohlbacherLab/dnpm-dip-api-gateway/blob/main/app/controllers/README.md#json-schema-of-patient-record-payloads]). The cardinalities are currently based on assumptions. If the eventual specifications for model project data are stricter in terms of "data set completeness", i.e. more elements are made mandatory even on the syntactic le
vel, our DTO structure and JSON schema will be adapted accordingly.

**Comment by lucienclin** [comment]
I added explanatory notes to the [ETL API Docs](https://github.com/KohlbacherLab/dnpm-dip-api-gateway/blob/main/app/controllers/README.md#upload-a-patient-record)
